apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster2

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 18.1.3
    releaseName: app1
    namespace: default
    valuesFile: values.yml

resources:
  - ./manifest.yml
