apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: cluster1-app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/WinterNis/test-dl.git
    targetRevision: tryouts
    path: withoutfactorization/cluster-1/app1
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
