apiVersion: apps/v1
kind: Deployment
metadata:
  name: subapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: subapp1
  template:
    metadata:
      labels:
        deployment: subapp1
    spec:
      containers:
        - name: the-container
          image: monopole/hello:1
          command: ["/hello", "--port=8080"]
          ports:
            - containerPort: 8080
          env:
            - name: ALT_GREETING
              valueFrom:
                configMapKeyRef:
                  name: subapp1
                  key: altGreeting
---
kind: Service
apiVersion: v1
metadata:
  name: subapp1
spec:
  selector:
    deployment: subapp1
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31013
      port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: subapp1
data:
  altGreeting: "Good Morning cluster1 subapp1"
